version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "music-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-l1tx4r4itdr5"
s3_prefix = "music-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "StageName=\"dev\" MusicApiLambdaFunctionName=\"music-api\""
image_repositories = []
